apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
 name: testsa-role
 namespace: default
rules:
- apiGroups:
  - "*"
  resources:
#   - "*"
#  - pods
   - deployments
#  - secrets
  verbs:
#  - "*"
  - get
  - watch
  - list
